import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: "#0F172A",
          raised: "#1E293B",
          overlay: "#1A1E2F",
        },
        surfaceLight: {
          DEFAULT: "#F7F9FB",
          raised: "#FFFFFF",
          overlay: "#EEF2F6",
        },
        line: {
          DEFAULT: "#334155",
          strong: "#475569",
        },
        lineLight: {
          DEFAULT: "#E3E9EF",
          strong: "#C9D4DE",
        },
        ink: {
          DEFAULT: "#F8FAFC",
          muted: "#94A3B8",
          faint: "#64748B",
        },
        inkLight: {
          DEFAULT: "#101B2D",
          muted: "#4E6178",
          faint: "#8CA0B3",
        },
        gold: {
          DEFAULT: "#F59E0B",
          light: "#FBBF24",
          dark: "#D97706",
        },
        purple: {
          DEFAULT: "#8B5CF6",
          light: "#A78BFA",
          dark: "#7C3AED",
        },
        emerald: {
          DEFAULT: "#059669",
          light: "#10B981",
          dark: "#047857",
        },
        amber: {
          DEFAULT: "#D97706",
          light: "#F59E0B",
          dark: "#B45309",
        },
        red: {
          DEFAULT: "#DC2626",
          light: "#EF4444",
          dark: "#B91C1C",
        },
        azure: {
          DEFAULT: "#2563EB",
          light: "#3B82F6",
          dark: "#1D4ED8",
        },
      },
      fontFamily: {
        sans: [
          "IBM Plex Sans",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: [
          "IBM Plex Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "Liberation Mono",
          "monospace",
        ],
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.08), 0 4px 16px rgba(0,0,0,0.12)",
        pop: "0 12px 40px rgba(0,0,0,0.20)",
        inner: "inset 0 1px 2px rgba(0,0,0,0.08)",
      },
      keyframes: {
        "soft-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.55" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(6px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          from: { opacity: "0", transform: "translateX(-8px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(1)", opacity: "0.5" },
          "100%": { transform: "scale(2)", opacity: "0" },
        },
        "flow": {
          "0%": { strokeDashoffset: "0" },
          "100%": { strokeDashoffset: "16" },
        },
      },
      animation: {
        "pulse-glow": "soft-pulse 1.4s ease-in-out infinite",
        "fade-up": "fade-up 0.35s ease-out both",
        "slide-in": "slide-in 0.3s ease-out both",
        "scale-in": "scale-in 0.2s ease-out both",
        "pulse-ring": "pulse-ring 1.5s ease-out infinite",
        "flow": "flow 1s linear infinite",
      },
      transitionDuration: {
        "0": "0ms",
        "75": "75ms",
        "100": "100ms",
        "150": "150ms",
        "200": "200ms",
        "250": "250ms",
        "300": "300ms",
        "350": "350ms",
        "400": "400ms",
        "500": "500ms",
        "700": "700ms",
        "1000": "1000ms",
      },
      spacing: {
        "0": "0",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "9": "2.25rem",
        "10": "2.5rem",
        "12": "3rem",
        "14": "3.5rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
        "28": "7rem",
        "32": "8rem",
        "36": "9rem",
        "40": "10rem",
        "44": "11rem",
        "48": "12rem",
        "52": "13rem",
        "56": "14rem",
        "60": "15rem",
        "64": "16rem",
        "72": "18rem",
        "80": "20rem",
        "96": "24rem",
      },
      fontSize: {
        "xs": ["0.75rem", { lineHeight: "1.5", letterSpacing: "0.02em" }],
        "sm": ["0.875rem", { lineHeight: "1.5", letterSpacing: "0.01em" }],
        "base": ["1rem", { lineHeight: "1.5", letterSpacing: "0" }],
        "lg": ["1.125rem", { lineHeight: "1.5", letterSpacing: "-0.01em" }],
        "xl": ["1.25rem", { lineHeight: "1.4", letterSpacing: "-0.01em" }],
        "2xl": ["1.5rem", { lineHeight: "1.3", letterSpacing: "-0.02em" }],
        "3xl": ["1.875rem", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "4xl": ["2.25rem", { lineHeight: "1.1", letterSpacing: "-0.03em" }],
        "5xl": ["3rem", { lineHeight: "1.05", letterSpacing: "-0.03em" }],
        "6xl": ["3.75rem", { lineHeight: "1", letterSpacing: "-0.04em" }],
      },
      borderRadius: {
        "none": "0",
        "sm": "0.25rem",
        "DEFAULT": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "9999px",
      },
      zIndex: {
        "0": "0",
        "10": "10",
        "20": "20",
        "30": "30",
        "40": "40",
        "50": "50",
      },
    },
  },
  plugins: [],
};

export default config;
